### ISSUE TITLE
Error while Debug

### ISSUE THREAD

**Issue by userdevil** [ahmadalzoabi/Fruit_Market#1]
/C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core-1.24.0/lib/src/firebase_app.dart:18:25: Error: Member not found: 'FirebaseAppPlatform.verifyExtends'.
    FirebaseAppPlatform.verifyExtends(_delegate);
                        ^^^^^^^^^^^^^
/C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/cloud_firestore_web-2.8.10/lib/src/utils/web_utils.dart:71:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
/C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_auth_web-4.6.1/lib/src/utils/web_utils.dart:263:9: Error: Method not found: 'FallThroughError'.
  throw FallThroughError();
        ^^^^^^^^^^^^^^^^
/C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/cloud_firestore_platform_interface-5.7.7/lib/src/platform_interface/utils/load_bundle_task_state.dart:13:13: Error: Method not found: 'FallThroughError'.
      throw FallThroughError();
            ^^^^^^^^^^^^^^^^
/C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_auth_platform_interface-6.10.1/lib/src/action_code_info.dart:65:15: Error: The method 'FallThroughError' isn't defined for the class 'ActionCodeInfo'.
 - 'ActionCodeInfo' is from 'package:firebase_auth_platform_interface/src/action_code_info.dart' ('/C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/firebase_auth_platform_interface-6.10.1/lib/src/action_code_info.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FallThroughError'.
        throw FallThroughError();
              ^^^^^^^^^^^^^^^^
Failed to compile application.

please help me to fix this error

**Comment by a7madZ3Dev** [comment]
I think in my project Some of the plugins were running on older outdated packages and there has been a major version upgrade, and When running (flutter pub upgrade), it only upgrades to the latest minor version. To fix this, do this:
`flutter pub upgrade --major-versions`
also please add this line under dependency_overrides in your pubspec.yaml to force install 4.5.1 version:
`firebase_core_platform_interface: 4.5.1`
4.5.2 has major changes, which was being automatically downloaded by firebase_core

**Comment by userdevil** [comment]
thank you for helping me to fix the issue i have another issue also while building the apk 
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @418a3cb9

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 38s`

i have tried to fix this in many ways but i have failed

**Comment by a7madZ3Dev** [comment]
Basically, you made my old project with lower JDK versions and I think you have higher JDK versions installed currently in your system.

You must be using a JDK version that is supported by the Gradle Version.

1-Check your JDK Version from C:\Program Files\Java. In Some Cases, It Could be  JDK-17.0.2

2-Check The Respective Gradle version for your JDK : [Gradel Versions](https://docs.gradle.org/current/userguide/compatibility.html)

3-Open gradle-wrapper.properties from .\android\gradle\wrapper\
![help](https://github.com/a7madZ3Dev/Fruit_Market/assets/39240890/fdfd4a0d-ae1b-4e02-a18c-0b83c6f3e411)

and change the distributionUrl to your required gradle version

e.g. for JDK 17

`distributionUrl = https\://services.gradle.org/distributions/gradle-7.3-all.zip`

4-Open build.gradle from .\android\build.gradle
![help2](https://github.com/a7madZ3Dev/Fruit_Market/assets/39240890/c5adf781-fffa-4e1a-8ce7-e82f259c6cd3)
and change the plugin in the class path to the one according to your gradle version

e.g.
```
classpath("com.android.tools.build:gradle:4.2.2") for Gradle 6.7.1+
classpath("com.android.tools.build:gradle:7.0.0") for Gradle 7+
```
Check the Compatible Plugin for your Gradle version at [Update Gradle](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle)

5-run the following command:
`npx react-native run-android`

**Comment by userdevil** [comment]
thank you.
